.\" $Copyright: $
.\" Copyright (c) 1996 - 1999 by Steve Baker
.\" All Rights reserved
.\"
.\" This software is provided as is without any express or implied
.\" warranties, including, without limitation, the implied warranties
.\" of merchantability and fitness for a particular purpose.
.\"
...
.V= $Header: tree.1 1.3 1996 - 1999 $
.TH TREE 1 "\*(V)" "UNIX Programmer's Manual"
.SH NAME
tree \- list contents of directories in a tree-like format.
.SH SYNOPSIS
\fBtree\fP [ \fB-adfgilnopqstuxACDFNS\fP ] [ \fB-L\fP \fIlevel\fP [ \fB-R\fP ]] [ \fB-H\fP \fIbaseHREF\fP ] [ \fB-P\fP \fIpattern\fP ] [ \fB-I\fP \fIpattern\fP ] [ \fIdirectory\fP ... ]
.br
.SH DESCRIPTION
\fITree\fP is a recursive directory listing program that produces a depth
indented listing of files, which is colorized ala \fIdircolors\fP if the \fBLS_COLORS\fP
environment variable is set and output is to tty.  With no arguments,
\fItree\fP lists the files in the current directory.  When directory
arguments are given, \fItree\fP lists all the files and/or directories found
in the given directories each in turn.  Upon completion of listing all
files/directories found, \fItree\fP returns the total number of files and/or
directories listed.

By default, when a symbolic link is encountered, the path that the symbolic
link refers to is printed after the name of the link in the format:
.br

    name -> real-path
.br

If the `\fB-l\fP' option is given and the symbolic link refers to an actual
directory, then \fItree\fP will follow the path of the symbolic link as if
it were a real directory.
.br

.SH OPTIONS
\fITree\fP understands the following command line switches:

.TP
.B --help
Outputs a verbose usage listing.
.PP
.TP
.B --version
Outputs the version of tree.
.PP
.TP
.B -a
All files are printed.  By default tree does not print hidden files (those
beginning with a dot `.').  In no event does tree print the file system
constructs `.' (current directory) and `..' (previous directory).
.PP
.TP
.B -d
List directories only.
.PP
.TP
.B -f
Prints the full path prefix for each file.
.PP
.TP
.B -i
Makes tree not print the indentation lines, useful when used in conjunction
with the \fB-f\fP option.
.PP
.TP
.B -l
Follows symbolic links if they point to directories, as if they were
directories. Symbolic links that will result in recursion are avoided when
detected.
.PP
.TP
.B -x
Stay on the current file-system only.  Ala \fBfind \fI-xdev\fP.
.PP
.TP
\fB-P \fIpattern\fP
List only those files that match the wild-card \fIpattern\fP.  Note: you must use
the \fI-a\fP option to also consider those files beginning with a dot `.' for
matching.  Valid wildcard operators are `*' (any zero or more characters), `?' (any
single character), `[...]' (any single character listed between brackets (optional -
(dash) for character range may be used: ex: [A-Z]), and `[^...]' (any single character
not listed in brackets).
.PP
.TP
.B -I \fIpattern\fP
Do not list those files that match the wild-card \fIpattern\fP.
.PP
.TP
.B -p
Print the protections for each file (as per ls -l).
.PP
.TP
.B -o \fIfilename\fP
Send output to \fIfilename\fP.
.PP
.TP
.B -s
Print the size of each file along with the name.
.PP
.TP
.B -u
Print the username, or UID # if no username is available, of the file.
.PP
.TP
.B -g
Print the group name, or GID # if no group name is available, of the file.
.PP
.TP
.B -D
Print the date of the last modification time for the file listed.
.PP
.TP
.B -F
Append a `/' for directories, a `=' for socket files, a `*' for executable files
and a `|' for FIFO's, as per ls -F
.PP
.TP
.B -q
Print non-printable characters in filenames as question marks instead of the default
carrot notation.
.PP
.TP
.B -N
Print non-printable characters as is instead of the default carrot notation.
.PP
.TP
.B -t
Sort the output by last modification time instead of alphabetically.
.PP
.TP
.B -n
Turn colorization off always, over-ridden by the \fB-C\fP option.
.PP
.TP
.B -C
Turn colorization on always, using built-in color defaults if the LS_COLORS
environment variable is not set.  Useful to colorize output to a pipe.
.PP
.TP
.B -A
Turn on ANSI line graphics hack when printing the indentation lines.
.PP
.TP
.B -S
Turn on ASCII line graphics (useful when using linux console mode fonts).
.PP
.TP
.B \fB-L \fIlevel\fP
Max display depth of the directory tree.
.PP
.TP
.B \fB-R\fP
Recursively cross down the tree each \fIlevel\fP directories (see \fB-L\fP
option), and at each of them execute \fBtree\fP again adding `-o 00Tree.html'
as a new option.
.PP
.TP
.B \fB-H \fIbaseHREF\fP
Turn on HTML output, including HTTP references. Useful for ftp sites.
\fIbaseHREF\fP gives the base ftp location when using HTML output. That is, the local
directory may be `/local/ftp/pub', but it must be referenced as
`ftp://hostname.organization.domain/pub' (\fIbaseHREF\fP should be
`ftp://hostname.organization.domain/'). Hint: don't use colorization and/or
ANSI lines with this option, and don't give more than one directory in the
directory list.
.PP
.br
.SH FILES
/etc/DIR_COLORS		System color database.
.br
~/.dircolors			Users color database.
.br

.SH ENVIRONMENT
\fBLS_COLORS\fP		Color information created by dircolors

.SH AUTHOR
Steve Baker (ice@mama.indstate.edu)
.br
HTML output hacked by Francesc Rocher (rocher@econ.udg.es)

.SH BUGS
None known.  Not heavily tested.  Could use a few more options, ala ls.

.SH SEE ALSO
.BR dircolors (1L),
.BR ls (1L),
.BR find (1L)
